reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs
  resources :posts, except: [:index]

end

reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id        :integer          not null, primary key
#  title     :string           not null
#  author_id :integer          not null
#  url       :string
#  content   :text
#  sub_id    :integer          not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, :sub_id, presence: true

  belongs_to :sub

  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User

end

reddit/app/models/sub.rb
#
# create_table "subs", force: :cascade do |t|
#   t.string   "title",        null: false
#   t.text     "description",  null: false
#   t.integer  "moderator_id", null: false
#   t.datetime "created_at"
#   t.datetime "updated_at"
# end

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  has_many :posts

  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User

  
end

reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  has_many :moderated_subs,
  foreign_key: :moderator_id,
  class_name: :Sub

  has_many :posts,
  foreign_key: :author_id,
  class_name: :Post

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    if user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token
  end


  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end


end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def show

  end

  def edit
    @post = Post.find_by_id(params[:id])
    if current_user.id == @post.author_id
      render :edit
    else
      redirect_to sub_url(@post.sub_id)
    end
  end

  def update

  end

  private
  def post_params
    params.require(:post).permit(:title, :author_id, :url, :content, :sub_id)
  end


end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      render :new
    else
      login!(@user)
      current_user
      redirect_to user_url(@user)
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end


end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index

  end

  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to
    else

    end
  end

  def show
    render :show
  end

  def edit

  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end


end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%if logged_in? %>
<%=button_to "Sign Out", session_url, method: :delete %>
<%else%>
<%=link_to "Sign In", new_session_url%>
<br>
<%=link_to "Sign Up", new_user_url %>
<%end%>

<%= yield %>


</body>
</html>

reddit/app/views/posts/new.html.erb
<h1>Creat a new post</h1>
<form action="<%=posts_url%>" method="post">
  <label name="title">Title<input type="text" name="post[title]"></label>

  <label name="author_id">Who's posting<input type="numerical" name="post[author_id]"></label>
  <label name="sub_id">Which sub<input type="numerical" name="post[sub_id]"></label>
  <input type="submit">
</form>

reddit/app/views/users/index.html.erb
<h1> Users! </h1>

reddit/app/views/users/new.html.erb
<h1>Create a new user</h1>
<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Username
    <input type="text" name="user[username]">
  </label>
<br>
<br>
  <label>Password <input type="password" name="user[password]"></label>
  <br>
  <input type="submit">
</form>

reddit/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>